type: google.api.Service
config_version: 3

http:
  rules:
    - selector: sound_transfer.SoundService.TestConnection 
      get: /SoundService/TestConnection 
    - selector: sound_transfer.SoundService.TranscribeFile
      get: /SoundService/TranscribeFile
    - selector: sound_transfer.SoundService.TranslateFile
      get: /SoundService/TranslateFile
    - selector: sound_transfer.SoundService.DiarizateFile
      get: /SoundService/DiarizateFile
    - selector: sound_transfer.SoundService.TranscribeLive
      get: /SoundService/TranscribeLive
    - selector: sound_transfer.SoundService.TranscribeLiveWeb
      get: /SoundService/TranscribeLiveWeb
    - selector: authentication.ClientService.Login
      get: /ClientService/Login
    - selector: authentication.ClientService.Register
      get: /ClientService/Register
    - selector: authentication.ClientService.GetTranslation
      get: /ClientService/GetTranslation
    - selector: authentication.ClientService.EditTranscription
      get: /ClientService/EditTranscription
    - selector: authentication.ClientService.DeleteTranscription
      get: /ClientService/DeleteTranscription
      
swagger:
  info:
    title: "Combined gRPC Documentation"
    description: | 
      This file includes gRPC for:
      - gRPC 1: Description of SoundService
      - gRPC 2: Description of ClientService
    version: "1.0.0"