# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sound_transfer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sound_transfer.proto\"1\n\x0cSoundRequest\x12\x12\n\nsound_data\x18\x01 \x01(\x0c\x12\r\n\x05\x66lags\x18\x02 \x03(\t\"\x1d\n\rSoundResponse\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x1b\n\x0bTextMessage\x12\x0c\n\x04text\x18\x04 \x01(\t2\xa6\x01\n\x0cSoundService\x12\x30\n\rSendSoundFile\x12\r.SoundRequest\x1a\x0e.SoundResponse\"\x00\x12.\n\x0eTestConnection\x12\x0c.TextMessage\x1a\x0c.TextMessage\"\x00\x12\x34\n\x0fStreamSoundFile\x12\r.SoundRequest\x1a\x0e.SoundResponse(\x01\x30\x01\x42\x1cZ\x1ainzynierka/server_servicesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sound_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\032inzynierka/server_services'
  _globals['_SOUNDREQUEST']._serialized_start=24
  _globals['_SOUNDREQUEST']._serialized_end=73
  _globals['_SOUNDRESPONSE']._serialized_start=75
  _globals['_SOUNDRESPONSE']._serialized_end=104
  _globals['_TEXTMESSAGE']._serialized_start=106
  _globals['_TEXTMESSAGE']._serialized_end=133
  _globals['_SOUNDSERVICE']._serialized_start=136
  _globals['_SOUNDSERVICE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
