// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

package authentication

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TextHistory struct {
	Transcription        string               `protobuf:"bytes,1,opt,name=transcription,proto3" json:"transcription,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Id                   int32                `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TextHistory) Reset()         { *m = TextHistory{} }
func (m *TextHistory) String() string { return proto.CompactTextString(m) }
func (*TextHistory) ProtoMessage()    {}
func (*TextHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{0}
}

func (m *TextHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TextHistory.Unmarshal(m, b)
}
func (m *TextHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TextHistory.Marshal(b, m, deterministic)
}
func (m *TextHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TextHistory.Merge(m, src)
}
func (m *TextHistory) XXX_Size() int {
	return xxx_messageInfo_TextHistory.Size(m)
}
func (m *TextHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_TextHistory.DiscardUnknown(m)
}

var xxx_messageInfo_TextHistory proto.InternalMessageInfo

func (m *TextHistory) GetTranscription() string {
	if m != nil {
		return m.Transcription
	}
	return ""
}

func (m *TextHistory) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *TextHistory) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type UserCredits struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredits) Reset()         { *m = UserCredits{} }
func (m *UserCredits) String() string { return proto.CompactTextString(m) }
func (*UserCredits) ProtoMessage()    {}
func (*UserCredits) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{1}
}

func (m *UserCredits) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredits.Unmarshal(m, b)
}
func (m *UserCredits) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredits.Marshal(b, m, deterministic)
}
func (m *UserCredits) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredits.Merge(m, src)
}
func (m *UserCredits) XXX_Size() int {
	return xxx_messageInfo_UserCredits.Size(m)
}
func (m *UserCredits) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredits.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredits proto.InternalMessageInfo

func (m *UserCredits) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserCredits) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StatusResponse struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Successful           bool     `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{2}
}

func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (m *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(m, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *StatusResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type LoginResponse struct {
	JWT                  string   `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
	Successful           bool     `protobuf:"varint,2,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{3}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetJWT() string {
	if m != nil {
		return m.JWT
	}
	return ""
}

func (m *LoginResponse) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type Id struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Id) Reset()         { *m = Id{} }
func (m *Id) String() string { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()    {}
func (*Id) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{4}
}

func (m *Id) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Id.Unmarshal(m, b)
}
func (m *Id) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Id.Marshal(b, m, deterministic)
}
func (m *Id) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Id.Merge(m, src)
}
func (m *Id) XXX_Size() int {
	return xxx_messageInfo_Id.Size(m)
}
func (m *Id) XXX_DiscardUnknown() {
	xxx_messageInfo_Id.DiscardUnknown(m)
}

var xxx_messageInfo_Id proto.InternalMessageInfo

func (m *Id) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type NewContent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewContent) Reset()         { *m = NewContent{} }
func (m *NewContent) String() string { return proto.CompactTextString(m) }
func (*NewContent) ProtoMessage()    {}
func (*NewContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{5}
}

func (m *NewContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewContent.Unmarshal(m, b)
}
func (m *NewContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewContent.Marshal(b, m, deterministic)
}
func (m *NewContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewContent.Merge(m, src)
}
func (m *NewContent) XXX_Size() int {
	return xxx_messageInfo_NewContent.Size(m)
}
func (m *NewContent) XXX_DiscardUnknown() {
	xxx_messageInfo_NewContent.DiscardUnknown(m)
}

var xxx_messageInfo_NewContent proto.InternalMessageInfo

func (m *NewContent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *NewContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_d0dbc99083440df2, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterType((*TextHistory)(nil), "TextHistory")
	proto.RegisterType((*UserCredits)(nil), "UserCredits")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*Id)(nil), "Id")
	proto.RegisterType((*NewContent)(nil), "NewContent")
	proto.RegisterType((*Empty)(nil), "Empty")
}

func init() { proto.RegisterFile("authentication.proto", fileDescriptor_d0dbc99083440df2) }

var fileDescriptor_d0dbc99083440df2 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x5d, 0x6b, 0x13, 0x41,
	0x14, 0xcd, 0x26, 0xa4, 0x4d, 0x6e, 0x9a, 0xa8, 0xd3, 0x20, 0x71, 0x1f, 0x34, 0x2c, 0x82, 0x41,
	0x71, 0x22, 0x2d, 0x08, 0x3e, 0xa6, 0x31, 0x6a, 0x8b, 0x48, 0xd9, 0x46, 0x04, 0x5f, 0x64, 0xba,
	0x7b, 0xbb, 0x0e, 0xee, 0xce, 0x2c, 0x33, 0x77, 0xad, 0xf1, 0xc1, 0x7f, 0xed, 0xbb, 0xec, 0x47,
	0xd6, 0x6c, 0x29, 0xf4, 0x6d, 0xcf, 0xdc, 0x33, 0xe7, 0xcc, 0xb9, 0x7b, 0x60, 0x2c, 0x32, 0xfa,
	0x8e, 0x8a, 0x64, 0x20, 0x48, 0x6a, 0xc5, 0x53, 0xa3, 0x49, 0xbb, 0x4f, 0x22, 0xad, 0xa3, 0x18,
	0xe7, 0x05, 0xba, 0xcc, 0xae, 0xe6, 0x24, 0x13, 0xb4, 0x24, 0x92, 0xb4, 0x24, 0x78, 0x7f, 0x60,
	0xb0, 0xc6, 0x5f, 0xf4, 0x41, 0x5a, 0xd2, 0x66, 0xc3, 0x9e, 0xc2, 0x90, 0x8c, 0x50, 0x36, 0x30,
	0x32, 0xcd, 0x65, 0x26, 0xce, 0xd4, 0x99, 0xf5, 0xfd, 0xe6, 0x21, 0x7b, 0x03, 0x10, 0x18, 0x14,
	0x84, 0xe1, 0x37, 0x41, 0x93, 0xf6, 0xd4, 0x99, 0x0d, 0x8e, 0x5c, 0x5e, 0x5a, 0xf1, 0xad, 0x15,
	0x5f, 0x6f, 0xad, 0xfc, 0x7e, 0xc5, 0x5e, 0x10, 0x1b, 0x41, 0x5b, 0x86, 0x93, 0xce, 0xd4, 0x99,
	0x75, 0xfd, 0xb6, 0x0c, 0xbd, 0x15, 0x0c, 0x3e, 0x5b, 0x34, 0x4b, 0x83, 0xa1, 0x24, 0xcb, 0x5c,
	0xe8, 0x65, 0x16, 0x8d, 0x12, 0x09, 0x56, 0xd6, 0x35, 0xce, 0x67, 0xa9, 0xb0, 0xf6, 0x5a, 0x9b,
	0xb0, 0xf0, 0xec, 0xfb, 0x35, 0xf6, 0xde, 0xc1, 0xe8, 0x82, 0x04, 0x65, 0xd6, 0x47, 0x9b, 0x6a,
	0x65, 0x91, 0x8d, 0xa1, 0x8b, 0xc6, 0x68, 0x53, 0xc9, 0x94, 0x80, 0x3d, 0x06, 0xb0, 0x59, 0x10,
	0xa0, 0xb5, 0x57, 0x59, 0x5c, 0xa8, 0xf4, 0xfc, 0x9d, 0x13, 0x6f, 0x01, 0xc3, 0x8f, 0x3a, 0x92,
	0xaa, 0x96, 0xb9, 0x0f, 0x9d, 0xb3, 0x2f, 0xeb, 0x4a, 0x24, 0xff, 0xbc, 0x53, 0x62, 0x0c, 0xed,
	0xd3, 0xb0, 0xca, 0xe9, 0xd4, 0x39, 0x5f, 0x03, 0x7c, 0xc2, 0xeb, 0xa5, 0x56, 0x84, 0x8a, 0x6e,
	0x4e, 0xd9, 0x04, 0xf6, 0x83, 0x72, 0x54, 0x25, 0xdb, 0x42, 0x6f, 0x1f, 0xba, 0xab, 0x24, 0xa5,
	0xcd, 0xd1, 0x5f, 0x07, 0x86, 0xcb, 0x58, 0xa2, 0xa2, 0x0b, 0x34, 0x3f, 0x65, 0x80, 0xec, 0x19,
	0x74, 0x8b, 0xb7, 0xb2, 0x03, 0xbe, 0xb3, 0x42, 0x77, 0xc4, 0x1b, 0x09, 0xbc, 0x16, 0x7b, 0x01,
	0x3d, 0x1f, 0x23, 0x69, 0x09, 0xcd, 0x0d, 0xee, 0x3d, 0xde, 0xdc, 0x9a, 0xd7, 0x62, 0xcf, 0x61,
	0xf4, 0x1e, 0x69, 0x9d, 0xff, 0xef, 0xb8, 0x68, 0x12, 0xdb, 0xe3, 0xc5, 0x0b, 0xdc, 0x03, 0xbe,
	0xd3, 0x14, 0xaf, 0xf5, 0xca, 0x61, 0xc7, 0xf0, 0x60, 0x15, 0xca, 0x92, 0x5c, 0x97, 0x63, 0xc0,
	0xff, 0x07, 0xbd, 0xcd, 0xe0, 0x25, 0x1c, 0xbe, 0xc5, 0x18, 0x09, 0x9b, 0xd7, 0x3a, 0xfc, 0x34,
	0xbc, 0x85, 0x7e, 0x72, 0x06, 0x0f, 0xa5, 0xe6, 0x91, 0x49, 0x03, 0xde, 0x6c, 0xf8, 0xc9, 0xe1,
	0xa2, 0x81, 0xcf, 0xf3, 0xde, 0x9d, 0x3b, 0x5f, 0x1f, 0x49, 0xf5, 0x7b, 0xa3, 0x24, 0x9a, 0x1f,
	0x62, 0xde, 0xbc, 0x71, 0xb9, 0x57, 0x74, 0xf3, 0xf8, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3c,
	0xf1, 0xc9, 0x2d, 0x2c, 0x03, 0x00, 0x00,
}
