/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.26.0
// source: sound_transfer.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = require('./sound_transfer_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.SoundServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.SoundServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.TextMessage,
 *   !proto.TextMessage>}
 */
const methodDescriptor_SoundService_TestConnection = new grpc.web.MethodDescriptor(
  '/SoundService/TestConnection',
  grpc.web.MethodType.UNARY,
  proto.TextMessage,
  proto.TextMessage,
  /**
   * @param {!proto.TextMessage} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.TextMessage.deserializeBinary
);


/**
 * @param {!proto.TextMessage} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.TextMessage)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.TextMessage>|undefined}
 *     The XHR Node Readable Stream
 */
proto.SoundServiceClient.prototype.testConnection =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/SoundService/TestConnection',
      request,
      metadata || {},
      methodDescriptor_SoundService_TestConnection,
      callback);
};


/**
 * @param {!proto.TextMessage} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.TextMessage>}
 *     Promise that resolves to the response
 */
proto.SoundServicePromiseClient.prototype.testConnection =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/SoundService/TestConnection',
      request,
      metadata || {},
      methodDescriptor_SoundService_TestConnection);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SoundRequest,
 *   !proto.SoundResponse>}
 */
const methodDescriptor_SoundService_SendSoundFile = new grpc.web.MethodDescriptor(
  '/SoundService/SendSoundFile',
  grpc.web.MethodType.UNARY,
  proto.SoundRequest,
  proto.SoundResponse,
  /**
   * @param {!proto.SoundRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SoundResponse.deserializeBinary
);


/**
 * @param {!proto.SoundRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SoundResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SoundResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.SoundServiceClient.prototype.sendSoundFile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/SoundService/SendSoundFile',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSoundFile,
      callback);
};


/**
 * @param {!proto.SoundRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SoundResponse>}
 *     Promise that resolves to the response
 */
proto.SoundServicePromiseClient.prototype.sendSoundFile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/SoundService/SendSoundFile',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSoundFile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SoundRequest,
 *   !proto.SoundStreamResponse>}
 */
const methodDescriptor_SoundService_SendSoundFileTranslation = new grpc.web.MethodDescriptor(
  '/SoundService/SendSoundFileTranslation',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.SoundRequest,
  proto.SoundStreamResponse,
  /**
   * @param {!proto.SoundRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SoundStreamResponse.deserializeBinary
);


/**
 * @param {!proto.SoundRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.SoundStreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.SoundServiceClient.prototype.sendSoundFileTranslation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/SoundService/SendSoundFileTranslation',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSoundFileTranslation);
};


/**
 * @param {!proto.SoundRequest} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.SoundStreamResponse>}
 *     The XHR Node Readable Stream
 */
proto.SoundServicePromiseClient.prototype.sendSoundFileTranslation =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/SoundService/SendSoundFileTranslation',
      request,
      metadata || {},
      methodDescriptor_SoundService_SendSoundFileTranslation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SoundRequest,
 *   !proto.SpeakerAndLine>}
 */
const methodDescriptor_SoundService_DiarizateSpeakers = new grpc.web.MethodDescriptor(
  '/SoundService/DiarizateSpeakers',
  grpc.web.MethodType.UNARY,
  proto.SoundRequest,
  proto.SpeakerAndLine,
  /**
   * @param {!proto.SoundRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.SpeakerAndLine.deserializeBinary
);


/**
 * @param {!proto.SoundRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SpeakerAndLine)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SpeakerAndLine>|undefined}
 *     The XHR Node Readable Stream
 */
proto.SoundServiceClient.prototype.diarizateSpeakers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/SoundService/DiarizateSpeakers',
      request,
      metadata || {},
      methodDescriptor_SoundService_DiarizateSpeakers,
      callback);
};


/**
 * @param {!proto.SoundRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SpeakerAndLine>}
 *     Promise that resolves to the response
 */
proto.SoundServicePromiseClient.prototype.diarizateSpeakers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/SoundService/DiarizateSpeakers',
      request,
      metadata || {},
      methodDescriptor_SoundService_DiarizateSpeakers);
};


module.exports = proto;

